language: r
r:
  - oldrel
  - release
  - devel
os: 
  - osx
  - linux
  
before_install: 
  - brew install llvm libomp
  - export CPP=/usr/local/opt/llvm/bin/clang
  
notifications:
  email:
   - never

branches:
  only:
   - master
